{
  "openapi": "3.0.0",
  "info": {
    "title": "Xano Metadata API - AUDIT LOGS",
    "description": "The <a href=\"https://docs.xano.com/xano-features/metadata-api\" target=\"_blank\">Metadata API</a> provides support\nto programatically manage your Xano instance and uses Access Tokens to\ncontrol access.",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "https://xhib-njau-6vza.d2.dev.xano.io/api:meta"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {}
  },
  "paths": {
    "/audit_log/search": {
      "post": {
        "operationId": "Xano Metadata API/audit_log/search|POST",
        "summary": "search audit logs across all workspaces with support for complex filtering and sorting",
        "description": "search audit logs across all workspaces with support for complex filtering and sorting\n<br /><br />\n<b>Authentication:</b> required",
        "tags": [
          "audit logs"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer",
                            "format": "int64",
                            "description": ""
                          },
                          "created_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "type": {
                            "type": "string",
                            "description": ""
                          },
                          "msg": {
                            "type": "string",
                            "description": ""
                          },
                          "label": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "description": ""
                            }
                          },
                          "data": {
                            "type": "object",
                            "description": "",
                            "nullable": true
                          },
                          "obj": {
                            "type": "object",
                            "properties": {
                              "type": {
                                "type": "string",
                                "description": ""
                              },
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              }
                            }
                          },
                          "user": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "email": {
                                "type": "string",
                                "description": "",
                                "format": "email",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          },
                          "workspace": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "name": {
                                "type": "string",
                                "description": ""
                              }
                            },
                            "nullable": true
                          },
                          "branch": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "label": {
                                "type": "string",
                                "description": "",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          }
                        }
                      }
                    },
                    "itemsReceived": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "curPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "nextPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "prevPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "offset": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "perPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "itemsTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "pageTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Input Error. Check the request payload for issues."
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Access denied. Additional privileges are needed access the requested resource."
          },
          "404": {
            "description": "Not Found. The requested resource does not exist."
          },
          "429": {
            "description": "Rate Limited. Too many requests."
          },
          "500": {
            "description": "Unexpected error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 1
                  },
                  "per_page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 50
                  },
                  "include_data": {
                    "type": "boolean",
                    "description": ""
                  },
                  "sort": {
                    "type": "object",
                    "description": ""
                  },
                  "search": {
                    "type": "object",
                    "description": ""
                  }
                },
                "example": {
                  "page": 1,
                  "per_page": 50,
                  "sort": {
                    "id": "desc"
                  },
                  "search": []
                }
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 1
                  },
                  "per_page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 50
                  },
                  "include_data": {
                    "type": "boolean",
                    "description": ""
                  },
                  "sort": {
                    "type": "object",
                    "description": ""
                  },
                  "search": {
                    "type": "object",
                    "description": ""
                  }
                },
                "example": {
                  "page": 1,
                  "per_page": 50,
                  "sort": {
                    "id": "desc"
                  },
                  "search": []
                }
              }
            }
          }
        }
      }
    },
    "/audit_log": {
      "get": {
        "operationId": "Xano Metadata API/audit_log|GET",
        "summary": "browse audit logs across all workspaces",
        "description": "browse audit logs across all workspaces\n<br /><br />\n<b>Authentication:</b> required",
        "tags": [
          "audit logs"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 1
            }
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 50
            }
          },
          {
            "name": "include_data",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer",
                            "format": "int64",
                            "description": ""
                          },
                          "created_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "type": {
                            "type": "string",
                            "description": ""
                          },
                          "msg": {
                            "type": "string",
                            "description": ""
                          },
                          "label": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "description": ""
                            }
                          },
                          "data": {
                            "type": "object",
                            "description": "",
                            "nullable": true
                          },
                          "obj": {
                            "type": "object",
                            "properties": {
                              "type": {
                                "type": "string",
                                "description": ""
                              },
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              }
                            }
                          },
                          "user": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "email": {
                                "type": "string",
                                "description": "",
                                "format": "email",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          },
                          "workspace": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "name": {
                                "type": "string",
                                "description": ""
                              }
                            },
                            "nullable": true
                          },
                          "branch": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "label": {
                                "type": "string",
                                "description": "",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          }
                        }
                      }
                    },
                    "itemsReceived": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "curPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "nextPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "prevPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "offset": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "perPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "itemsTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "pageTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Input Error. Check the request payload for issues."
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Access denied. Additional privileges are needed access the requested resource."
          },
          "404": {
            "description": "Not Found. The requested resource does not exist."
          },
          "429": {
            "description": "Rate Limited. Too many requests."
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    },
    "/workspace/{workspace_id}/audit_log/search": {
      "post": {
        "operationId": "Xano Metadata API/workspace/{workspace_id}/audit_log/search|POST",
        "summary": "Search audit logs using advanced filters and custom sorting options",
        "description": "Search audit logs using advanced filters and custom sorting options\n<br /><br />\n<b>Authentication:</b> required\n<br /><br />\n<b>Required API Scope:</b>\nWorkspace Log: Read",
        "tags": [
          "audit logs"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "workspace_id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer",
                            "format": "int64",
                            "description": ""
                          },
                          "created_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "type": {
                            "type": "string",
                            "description": ""
                          },
                          "msg": {
                            "type": "string",
                            "description": ""
                          },
                          "label": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "description": ""
                            }
                          },
                          "data": {
                            "type": "object",
                            "description": "",
                            "nullable": true
                          },
                          "obj": {
                            "type": "object",
                            "properties": {
                              "type": {
                                "type": "string",
                                "description": ""
                              },
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              }
                            }
                          },
                          "user": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "email": {
                                "type": "string",
                                "description": "",
                                "format": "email",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          },
                          "workspace": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "name": {
                                "type": "string",
                                "description": ""
                              }
                            },
                            "nullable": true
                          },
                          "branch": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "label": {
                                "type": "string",
                                "description": "",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          }
                        }
                      }
                    },
                    "itemsReceived": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "curPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "nextPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "prevPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "offset": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "perPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "itemsTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "pageTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Input Error. Check the request payload for issues."
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Access denied. Additional privileges are needed access the requested resource."
          },
          "404": {
            "description": "Not Found. The requested resource does not exist."
          },
          "429": {
            "description": "Rate Limited. Too many requests."
          },
          "500": {
            "description": "Unexpected error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 1
                  },
                  "per_page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 50
                  },
                  "include_data": {
                    "type": "boolean",
                    "description": ""
                  },
                  "sort": {
                    "type": "object",
                    "description": ""
                  },
                  "search": {
                    "type": "object",
                    "description": ""
                  }
                },
                "example": {
                  "page": 1,
                  "per_page": 50,
                  "sort": {
                    "id": "desc"
                  },
                  "search": []
                }
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 1
                  },
                  "per_page": {
                    "type": "integer",
                    "format": "int64",
                    "description": "",
                    "default": 50
                  },
                  "include_data": {
                    "type": "boolean",
                    "description": ""
                  },
                  "sort": {
                    "type": "object",
                    "description": ""
                  },
                  "search": {
                    "type": "object",
                    "description": ""
                  }
                },
                "example": {
                  "page": 1,
                  "per_page": 50,
                  "sort": {
                    "id": "desc"
                  },
                  "search": []
                }
              }
            }
          }
        }
      }
    },
    "/workspace/{workspace_id}/audit_log": {
      "get": {
        "operationId": "Xano Metadata API/workspace/{workspace_id}/audit_log|GET",
        "summary": "Retrieve workspace audit logs with pagination support",
        "description": "Retrieve workspace audit logs with pagination support\n<br /><br />\n<b>Authentication:</b> required\n<br /><br />\n<b>Required API Scope:</b>\nWorkspace Log: Read",
        "tags": [
          "audit logs"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "workspace_id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 1
            }
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 50
            }
          },
          {
            "name": "include_data",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer",
                            "format": "int64",
                            "description": ""
                          },
                          "created_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "timestamptz",
                            "description": ""
                          },
                          "type": {
                            "type": "string",
                            "description": ""
                          },
                          "msg": {
                            "type": "string",
                            "description": ""
                          },
                          "label": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "description": ""
                            }
                          },
                          "data": {
                            "type": "object",
                            "description": "",
                            "nullable": true
                          },
                          "obj": {
                            "type": "object",
                            "properties": {
                              "type": {
                                "type": "string",
                                "description": ""
                              },
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              }
                            }
                          },
                          "user": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "email": {
                                "type": "string",
                                "description": "",
                                "format": "email",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          },
                          "workspace": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "name": {
                                "type": "string",
                                "description": ""
                              }
                            },
                            "nullable": true
                          },
                          "branch": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64",
                                "description": ""
                              },
                              "label": {
                                "type": "string",
                                "description": "",
                                "nullable": true
                              }
                            },
                            "nullable": true
                          }
                        }
                      }
                    },
                    "itemsReceived": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "curPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "nextPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "prevPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": "",
                      "nullable": true
                    },
                    "offset": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "perPage": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "itemsTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    },
                    "pageTotal": {
                      "type": "integer",
                      "format": "int64",
                      "description": ""
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Input Error. Check the request payload for issues."
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Access denied. Additional privileges are needed access the requested resource."
          },
          "404": {
            "description": "Not Found. The requested resource does not exist."
          },
          "429": {
            "description": "Rate Limited. Too many requests."
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    }
  }
}